name: Publish

on:
  push:
    # tags: [ 'v*.*.*' ]
    branches: 245-github-actions-migrate

env:
  OTP_VERSION_SPEC: "21.1"
  ELIXIR_VERSION_SPEC: "1.9.4"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}

      - name: Publish
        run: mix hex.publish --yes